[package]
name = "yew-recaptcha-v3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
gloo-console = "0.2.1"
gloo-utils = "0.1.2"
anyhow = "1.0.61"
wasm-bindgen = "0.2.82"
js-sys = "0.3.59"
[dependencies.web-sys]
version = "0.3.58"
features = [
    "HtmlCanvasElement",
    "Element"
]